@echo off

call zip_init.cmd

set SOURSE_FOLDER_NAME=RSU-135
set SOURSE_FOLDER_PATH=%SOLUTION_BIN_PATH%\%SOURSE_FOLDER_NAME%

7z a "%DEST_NAME%_%SOURSE_FOLDER_NAME%_%USER_INPUT_STRING%" %SOURSE_FOLDER_PATH%\ -mhe=on 

::pause