@echo off

set SOLUTION_PROGRAMMING_PATH=g:\Programming
set SOLUTION_WORK_PATH=%SOLUTION_PROGRAMMING_PATH%\Work
set SOLUTION_BIN_PATH=%SOLUTION_PROGRAMMING_PATH%\_bin
set SOLUTION_SCRIPTS_PATH=%SOLUTION_PROGRAMMING_PATH%\Scripts


set BACK_UP_PATH=g:\_back_up
set BACK_UP_ZIP_PATH=%BACK_UP_PATH%\_bin
